# Generated by Django 4.1.2 on 2022-10-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Todo",
        ),
    ]
