# Generated by Django 4.1.2 on 2022-10-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_task_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
